build:
	@echo "No building required. Binary package."

build-indep:
	@echo "No building required. Binary package."

install:
	cp -av src/all/* ${DESTDIR}

clean:
	@echo "Cleaning not required. Binary package."

