#! /bin/sh
# postrm script 
#
# see: dh_installdeb(1)

set -e

if [ -f /usr/share/debconf/confmodule ]; then
. /usr/share/debconf/confmodule
fi
    
case "$1" in
    purge)
    ;;
    *)  
    ;;
esac    
            
                
#DEBHELPER#             
                
exit 0          

