build:
	@echo "No building required. Binary package."

buil-indep:
	@echo "No building required. Binary package."

install:
	#cp -av src/`dpkg --print-architecture`/* ${DESTDIR}
	cp -av src/any/* ${DESTDIR}
install-indep:
	#cp -av src/`dpkg --print-architecture`/* ${DESTDIR}
	cp -av src/any/* ${DESTDIR}

clean:
	@echo "Cleaning not required. Binary package."

