#! /bin/sh
# postrm script 
#
# see: dh_installdeb(1)

set -e

if [ -f /usr/share/debconf/confmodule ]; then
. /usr/share/debconf/confmodule
fi
    
case "$1" in
    remove|upgrade|deconfigure)
        update-alternatives --remove cpt-build-tut-01 /usr/bin/cpt-build-tut-01v1
    ;;
    *)  
    ;;
esac    
            
                
#DEBHELPER#             
                
exit 0          

